console.log("hello world");
let x = "abhishek";
console.log(x);
let y = "1020";
console.log(y);
let z = "1030";
console.log(z);
z = "1040";
console.log(z);
let w = "1045";
console.log(w);
r = "rehan";
console.log(typeof r);
console.log(typeof z);
let a = "2020";
console.log(typeof a);
name = "hihi";
console.log(typeof name);
u = 34;
console.log(typeof u);
d = 20;
console.log(typeof d);
r = 70;
console.log(typeof r);
